# Generated by Django 5.0.11 on 2025-03-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="event_tags", to="program.tag"
            ),
        ),
    ]
