# Generated by Django 5.0.11 on 2025-03-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0002_alter_eventtag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="program.tag"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[("category", "Category"), ("location", "Location"), ("meta", "Meta")],
                default="category",
                max_length=10,
            ),
        ),
    ]
