# Generated by Django 5.0.11 on 2025-03-02 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0003_tag_hidden_tag_parent_tag_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
    ]
