# Generated by Django 5.0.11 on 2025-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0004_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
