# Generated by Django 5.0.11 on 2025-03-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0005_event_hidden"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="related_page",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.page"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_url",
            field=models.URLField(blank=True),
        ),
    ]
