# Generated by Django 4.2.7 on 2023-11-19 18:02

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aktuelt", "0004_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="authors",
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to="aktuelt.author"),
        ),
    ]
