# Generated by Django 4.2.7 on 2023-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aktuelt", "0008_contributor_newspagecontributor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="date",
        ),
        migrations.AddField(
            model_name="newspage",
            name="custom_published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publish override"),
        ),
        migrations.AddField(
            model_name="newspage",
            name="custom_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Update override"),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="default_contribution_type",
            field=models.CharField(
                choices=[
                    ("Text", "Text"),
                    ("Photography", "Photography"),
                    ("Video", "Video"),
                    ("Audio", "Audio"),
                    ("Other", "Other"),
                ],
                default="Text",
                max_length=250,
            ),
        ),
    ]
