# Generated by Django 4.2.16 on 2024-11-13 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aktuelt", "0009_remove_newspage_date_newspage_custom_published_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsPageGalleryImage",
        ),
    ]
