# Generated by Django 5.0.11 on 2025-02-25 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aktuelt", "0010_delete_newspagegalleryimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="custom_updated_at",
        ),
    ]
