# Generated by Django 5.0.11 on 2025-03-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aktuelt", "0011_remove_newspage_custom_updated_at"),
        ("home", "0004_customimage_customrendition"),
    ]

    operations = [
        # Move copy existing images from wagtailimages.Image to home.CustomImage before changing dependencies
        # Not deleting any images, as this can more safely be done later
        # TODO: Get rid of this migration (manually adjust earlier migrations to point to new image model immediately?) to avoid strange issues when developing locally
        migrations.RunSQL(
            """
            INSERT INTO home_customimage (id, title, file, description, width, height, created_at, focal_point_x, focal_point_y, focal_point_width, focal_point_height, file_size, file_hash, uncroppable, collection_id, uploaded_by_user_id)
            SELECT id, title, file, description, width, height, created_at, focal_point_x, focal_point_y, focal_point_width, focal_point_height, file_size, file_hash, False, collection_id, uploaded_by_user_id
            FROM wagtailimages_image
            """,
            "",
        ),
        # Postgres specific sequence reset, adjust if using with another database
        migrations.RunSQL(
            """
            SELECT setval(pg_get_serial_sequence('"home_customimage"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "home_customimage";
            """,
            """
            SELECT setval(pg_get_serial_sequence('"home_customimage"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "home_customimage";
            """,
        ),
        migrations.AlterField(
            model_name="contributor",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
            ),
        ),
    ]
