# Generated by Django 5.0.11 on 2026-03-24 22:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("rules", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Competition Rule",
                "verbose_name_plural": "Competition Rules",
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", models.TextField()),
                ("signup_link", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CompetitionRuleSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "competition",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_rule_sets",
                        to="konkurranse.competition",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_links",
                        to="konkurranse.ruleset",
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "rule_set")},
            },
        ),
        migrations.CreateModel(
            name="CompetitionCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description of this competition category")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CompetitionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "group",
                    models.CharField(
                        choices=[("creative", "Creative"), ("esport", "Esport")],
                        help_text="Which main group this competition type belongs to",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Type",
                "verbose_name_plural": "Competition Types",
                "ordering": ["group", "name"],
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="competition_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The type of this competition",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="konkurranse.competitiontype",
            ),
        ),
    ]
