# Generated by Django 5.0.11 on 2026-03-24 22:59

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("konkurranse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Optional name (e.g., '1st place', 'Best Design')", max_length=255
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="Prize value (can be a number or text like 'Gaming PC')", max_length=255
                    ),
                ),
                (
                    "competition",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_prizes",
                        to="konkurranse.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
