# Generated by Django 5.0.11 on 2025-04-11 22:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [("hero", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["aktuelt.NewsPage", "praktisk.InfoPage"]},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Text", "required": False}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Button text", "required": False}),
                    3: ("wagtail.blocks.URLBlock", (), {"label": "Button url", "required": False}),
                    4: ("wagtail.blocks.StructBlock", [[("text", 1), ("button_text", 2), ("button_url", 3)]], {}),
                    5: ("wagtail.blocks.StructBlock", [[("page", 0), ("cta", 4)]], {}),
                },
                null=True,
            ),
        ),
    ]
