# Generated by Django 5.0.11 on 2025-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_customimage_customrendition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customimage",
            options={
                "permissions": [("choose_image", "Can choose image")],
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.AlterField(
            model_name="customimage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
