# Generated by Django 4.2.7 on 2023-12-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aktuelt", "0009_remove_newspage_date_newspage_custom_published_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoIndexPage",
            fields=[
                (
                    "newsindexpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="aktuelt.newsindexpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("aktuelt.newsindexpage",),
        ),
        migrations.CreateModel(
            name="InfoPage",
            fields=[
                (
                    "newspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="aktuelt.newspage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("aktuelt.newspage",),
        ),
    ]
