# Generated by Django 4.2.19 on 2025-02-06 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("praktisk", "0001_initial"),
    ]

    operations = [
        # migrations.RemoveField(
        #    model_name="infopage",
        #    name="newspage_ptr",
        # ),
        migrations.DeleteModel(
            name="InfoIndexPage",
        ),
        migrations.DeleteModel(
            name="InfoPage",
        ),
    ]
