name: build-image
on:
  push:
    branches:
      - 'main'
      - 'automatic-build'

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  build-image:
    name: build image
    runs-on: ubuntu-latest
    needs: [ci]  # require tests to pass before build runs
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build backend image for amd64
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          APP_ENV=production
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/wagtail-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build nginx image for amd64
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          APP_ENV=nginx-production
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/nginx-static:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max